name: rs-py3_8
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.12.2
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=24.2
  - pthread-stubs=0.3
  - python=3.8.20
  - readline=8.3
  - setuptools=75.1.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.44.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - asciitree==0.3.3
      - bioframe==0.8.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - contourpy==1.1.1
      - cooler==0.10.2
      - cooltools==0.7.1
      - cycler==0.12.1
      - cython==3.2.2
      - cytoolz==1.0.1
      - dill==0.4.0
      - fonttools==4.57.0
      - h5py==3.11.0
      - hic-straw==1.3.1
      - hicrust==0.1.0
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - llvmlite==0.41.1
      - matplotlib==3.7.5
      - maturin==1.10.2
      - multiprocess==0.70.18
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.24.4
      - packaging==25.0
      - pandas==2.0.3
      - pillow==10.4.0
      - py2bit==0.3.3
      - pybind11==3.0.1
      - pyfaidx==0.9.0.3
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - requests==2.32.4
      - rstrainer==0.1.0
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - simplejson==3.20.2
      - six==1.17.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tomli==2.3.0
      - toolz==1.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.2.3
      - zipp==3.20.2
