[project]
name = "rstrainer"
version = "0.1.0"
requires-python = ">=3.8"

[build-system]
requires = ["maturin>=1.5"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
module-name = "rstrainer"
